apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: india-quiz-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/india-quiz-app
    targetRevision: HEAD
    path: helm/india-quiz
  destination:
    server: https://kubernetes.default.svc
    namespace: quiz-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true