apiVersion: apps/v1
kind: Deployment
metadata:
  name: india-quiz-app
  labels:
    app: india-quiz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: india-quiz
  template:
    metadata:
      labels:
        app: india-quiz
    spec:
      containers:
      - name: quiz-app
        image: learningdevops33/india-quiz:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"